### ISSUE TITLE
python3.6 使用 update_function 如果使用了 zipFile 参数会报错

### ISSUE THREAD

**Issue by fushang318** [aliyun/fc-python-sdk#11]
堆栈错误如下
```
Traceback (most recent call last):
  File "deploy.py", line 33, in <module>
    client.update_function(service_name, "user_login", runtime="python2.7", handler="user.login", codeZipFile="code.zip")
  File "/Users/lifei/.pyenv/versions/3.6.0/lib/python3.6/site-packages/fc/client.py", line 442, in update_function
    r = self._do_request(method, path, headers, body=json.dumps(payload).encode('utf-8'))
  File "/Users/lifei/.pyenv/versions/3.6.0/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/lifei/.pyenv/versions/3.6.0/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/lifei/.pyenv/versions/3.6.0/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/lifei/.pyenv/versions/3.6.0/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

**Comment by rsonghuster** [comment]
好的，我这边跟进看下，目前发现还有一个地方有上面类似的错误，我这边统一改下，谢谢！

**Comment by fushang318** [comment]
@rsonghuster   codeDir 参数也有这个问题

**Comment by rsonghuster** [comment]
@fushang318  pypi 源已经更新 pip install --upgrade aliyun-fc
感谢您的建议
